export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS';
export const FETCH_MOVIES_REQUEST = 'FETCH_MOVIES_SUCCESS';
export const FETCH_MOVIES_FAILURE = 'FETCH_MOVIES_FAILURE';

export const LOAD_MOVIES = 'LOAD_MOVIES';
export const RESET_FILTER = 'RESET_FILTER';
export const FILTER_MOVIES = 'FILTER_MOVIES';
export const UPDATE_MOVIE_SUCCESS = 'UPDATE_MOVIE_SUCCESS';